set(APRG_LOCAL_SCREEN_MONITORING_SOURCE_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/src)

set(APRG_LOCAL_SCREEN_MONITORING_TEST_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/tst)

set(APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCE_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/srcWindows)

set(APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TEST_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/tstWindows)

set(APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCE_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/srcLinux)

set(APRG_LOCAL_SCREEN_MONITORING_LINUX_TEST_DIRECTORY ${APRG_LOCAL_SCREEN_MONITORING_DIR}/tstLinux)

print_status("Looking for sources C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_SOURCES ${APRG_LOCAL_SCREEN_MONITORING_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_TESTS ${APRG_LOCAL_SCREEN_MONITORING_TEST_DIRECTORY})

if(WIN32)
    print_status(
        "Looking for windows sources C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCE_DIRECTORY}]")
    get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCES
                                    ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCE_DIRECTORY})

    print_status("Looking for windows tests C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TEST_DIRECTORY}]")
    get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TESTS
                                    ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TEST_DIRECTORY})

    set(APRG_LOCAL_SCREEN_MONITORING_SOURCES ${APRG_LOCAL_SCREEN_MONITORING_SOURCES}
                                             ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCES})
    set(APRG_LOCAL_SCREEN_MONITORING_TESTS ${APRG_LOCAL_SCREEN_MONITORING_TESTS}
                                           ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TESTS})
    set(APRG_LOCAL_SCREEN_MONITORING_INCLUDE_DIRECTORIES ${APRG_LOCAL_SCREEN_MONITORING_SOURCE_DIRECTORY}
                                                         ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_SOURCE_DIRECTORY})
    set(APRG_LOCAL_SCREEN_MONITORING_TEST_INCLUDE_DIRECTORIES ${APRG_LOCAL_SCREEN_MONITORING_TEST_DIRECTORY}
                                                              ${APRG_LOCAL_SCREEN_MONITORING_WINDOWS_TEST_DIRECTORY})
elseif(UNIX)
    print_status("Looking for linux sources C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCE_DIRECTORY}]")
    get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCES
                                    ${APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCE_DIRECTORY})

    print_status("Looking for linux tests C/C++ files in: [${APRG_LOCAL_SCREEN_MONITORING_LINUX_TEST_DIRECTORY}]")
    get_source_files_from_directory(APRG_LOCAL_SCREEN_MONITORING_LINUX_TESTS
                                    ${APRG_LOCAL_SCREEN_MONITORING_LINUX_TEST_DIRECTORY})

    set(APRG_LOCAL_SCREEN_MONITORING_SOURCES ${APRG_LOCAL_SCREEN_MONITORING_SOURCES}
                                             ${APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCES})
    set(APRG_LOCAL_SCREEN_MONITORING_TESTS ${APRG_LOCAL_SCREEN_MONITORING_TESTS}
                                           ${APRG_LOCAL_SCREEN_MONITORING_LINUX_TESTS})
    set(APRG_LOCAL_SCREEN_MONITORING_INCLUDE_DIRECTORIES ${APRG_LOCAL_SCREEN_MONITORING_SOURCE_DIRECTORY}
                                                         ${APRG_LOCAL_SCREEN_MONITORING_LINUX_SOURCE_DIRECTORY})
    set(APRG_LOCAL_SCREEN_MONITORING_TEST_INCLUDE_DIRECTORIES ${APRG_LOCAL_SCREEN_MONITORING_TEST_DIRECTORY}
                                                              ${APRG_LOCAL_SCREEN_MONITORING_LINUX_TEST_DIRECTORY})
endif()

set(APRG_LOCAL_SCREEN_MONITORING_SOURCES_AND_TESTS ${APRG_LOCAL_SCREEN_MONITORING_SOURCES}
                                                   ${APRG_LOCAL_SCREEN_MONITORING_TESTS})
