set(APRG_AUDIO_SOURCE_DIRECTORY ${APRG_AUDIO_DIR}/src)

set(APRG_AUDIO_TEST_DIRECTORY ${APRG_AUDIO_DIR}/tst)

set(APRG_AUDIO_MAIN_DIRECTORY ${APRG_AUDIO_DIR}/main)

set(APRG_AUDIO_INCLUDE_DIRECTORIES ${APRG_AUDIO_SOURCE_DIRECTORY})

set(APRG_AUDIO_TEST_INCLUDE_DIRECTORIES ${APRG_AUDIO_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_AUDIO_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_AUDIO_SOURCES ${APRG_AUDIO_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_AUDIO_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_AUDIO_TESTS ${APRG_AUDIO_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${APRG_AUDIO_MAIN_DIRECTORY}]")
get_source_files_from_directory(APRG_AUDIO_MAIN_SOURCES ${APRG_AUDIO_MAIN_DIRECTORY})

set(APRG_AUDIO_SOURCES_AND_TESTS ${APRG_AUDIO_SOURCES} ${APRG_AUDIO_TESTS})
