set(APRG_MODELING_SOURCE_DIRECTORY ${APRG_MODELING_DIR}/src)

set(APRG_MODELING_TEST_DIRECTORY ${APRG_MODELING_DIR}/tst)

set(APRG_MODELING_INCLUDE_DIRECTORIES ${APRG_MODELING_SOURCE_DIRECTORY})

set(APRG_MODELING_TEST_INCLUDE_DIRECTORIES ${APRG_MODELING_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_MODELING_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_MODELING_SOURCES ${APRG_MODELING_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_MODELING_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_MODELING_TESTS ${APRG_MODELING_TEST_DIRECTORY})

set(APRG_MODELING_SOURCES_AND_TESTS ${APRG_MODELING_SOURCES} ${APRG_MODELING_TESTS})
