set(PERFORMANCE_ANALYZER_SOURCE_DIRECTORY
    ${PERFORMANCE_ANALYZER_DIR}/src
)

set(PERFORMANCE_ANALYZER_TEST_DIRECTORY
    ${PERFORMANCE_ANALYZER_DIR}/tst
)

set(PERFORMANCE_ANALYZER_INCLUDE_DIRECTORIES
    ${PERFORMANCE_ANALYZER_SOURCE_DIRECTORY}
)

set(PERFORMANCE_ANALYZER_TEST_INCLUDE_DIRECTORIES
    ${PERFORMANCE_ANALYZER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${PERFORMANCE_ANALYZER_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(PERFORMANCE_ANALYZER_SOURCES PERFORMANCE_ANALYZER_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${PERFORMANCE_ANALYZER_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(PERFORMANCE_ANALYZER_TESTS PERFORMANCE_ANALYZER_TEST_DIRECTORY)

set(PERFORMANCE_ANALYZER_SOURCES_AND_TESTS
    ${PERFORMANCE_ANALYZER_SOURCES}
    ${PERFORMANCE_ANALYZER_TESTS}
)
