set(PERFORMANCE_ANALYZER_SOURCE_DIRECTORY ${PERFORMANCE_ANALYZER_DIR}/src)

set(PERFORMANCE_ANALYZER_TEST_DIRECTORY ${PERFORMANCE_ANALYZER_DIR}/tst)

set(PERFORMANCE_ANALYZER_INCLUDE_DIRECTORIES ${PERFORMANCE_ANALYZER_SOURCE_DIRECTORY})

set(PERFORMANCE_ANALYZER_TEST_INCLUDE_DIRECTORIES ${PERFORMANCE_ANALYZER_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${PERFORMANCE_ANALYZER_SOURCE_DIRECTORY}]")
get_source_files_from_directory(PERFORMANCE_ANALYZER_SOURCES ${PERFORMANCE_ANALYZER_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${PERFORMANCE_ANALYZER_TEST_DIRECTORY}]")
get_source_files_from_directory(PERFORMANCE_ANALYZER_TESTS ${PERFORMANCE_ANALYZER_TEST_DIRECTORY})

set(PERFORMANCE_ANALYZER_SOURCES_AND_TESTS ${PERFORMANCE_ANALYZER_SOURCES} ${PERFORMANCE_ANALYZER_TESTS})
