

# Assign Sack Directory
set(EXTERNAL_SACK_DIRECTORY ${APRG_DIR}/ZZZ_OldProjects/Wbts/ExternalSacks/src)

set(EXTERNAL_SACK_DIRECTORIES
${EXTERNAL_SACK_DIRECTORY}
${EXTERNAL_SACK_DIRECTORY}/MCU/Definitions
${EXTERNAL_SACK_DIRECTORY}/MCU/Messages
${EXTERNAL_SACK_DIRECTORY}/MCU/ServiceInterface
${EXTERNAL_SACK_DIRECTORY}/COMMON/Definitions
${EXTERNAL_SACK_DIRECTORY}/COMMON/Messages
${EXTERNAL_SACK_DIRECTORY}/COMMON/ServiceInterface)

PRINT_STATUS("Looking for EXTERNAL_SACK_DIRECTORY C/C++ files in: [${EXTERNAL_SACK_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(EXTERNAL_SACKS ${EXTERNAL_SACK_DIRECTORY})
