set(DMEAS_TIMER_STACK_SOURCE_DIRECTORY ${DMEAS_TIMER_STACK_DIR}/src)

set(DMEAS_TIMER_STACK_TEST_DIRECTORY ${DMEAS_TIMER_STACK_DIR}/tst)

set(DMEAS_TIMER_STACK_MAIN_DIRECTORY ${DMEAS_TIMER_STACK_DIR}/main)

set(DMEAS_TIMER_STACK_INCLUDE_DIRECTORIES ${DMEAS_TIMER_STACK_SOURCE_DIRECTORY})

set(DMEAS_TIMER_STACK_TEST_INCLUDE_DIRECTORIES ${DMEAS_TIMER_STACK_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${DMEAS_TIMER_STACK_SOURCE_DIRECTORY}]")
get_source_files_from_directory(DMEAS_TIMER_STACK_SOURCES ${DMEAS_TIMER_STACK_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${DMEAS_TIMER_STACK_TEST_DIRECTORY}]")
get_source_files_from_directory(DMEAS_TIMER_STACK_TESTS ${DMEAS_TIMER_STACK_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${DMEAS_TIMER_STACK_MAIN_DIRECTORY}]")
get_source_files_from_directory(DMEAS_TIMER_STACK_MAIN_SOURCES ${DMEAS_TIMER_STACK_MAIN_DIRECTORY})

set(DMEAS_TIMER_STACK_SOURCES_AND_TESTS ${DMEAS_TIMER_STACK_SOURCES} ${DMEAS_TIMER_STACK_TESTS})
