set(LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY ${LRM_ALLOCATION_SIMULATOR_DIR}/src)

set(LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY ${LRM_ALLOCATION_SIMULATOR_DIR}/tst)

set(LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY ${LRM_ALLOCATION_SIMULATOR_DIR}/main)

set(LRM_ALLOCATION_SIMULATOR_INCLUDE_DIRECTORIES ${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY})

set(LRM_ALLOCATION_SIMULATOR_TEST_INCLUDE_DIRECTORIES ${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY}]")
get_source_files_from_directory(LRM_ALLOCATION_SIMULATOR_SOURCES ${LRM_ALLOCATION_SIMULATOR_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY}]")
get_source_files_from_directory(LRM_ALLOCATION_SIMULATOR_TESTS ${LRM_ALLOCATION_SIMULATOR_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY}]")
get_source_files_from_directory(LRM_ALLOCATION_SIMULATOR_MAIN_SOURCES ${LRM_ALLOCATION_SIMULATOR_MAIN_DIRECTORY})

set(LRM_ALLOCATION_SIMULATOR_SOURCES_AND_TESTS ${LRM_ALLOCATION_SIMULATOR_SOURCES} ${LRM_ALLOCATION_SIMULATOR_TESTS})
