set(BOOST_TEST_DIRECTORY
    ${BOOST_DIR}/tst
)

set(BOOST_TEST_INCLUDE_DIRECTORIES
    ${BOOST_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for TST C/C++ files in: [${BOOST_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(BOOST_TESTS BOOST_TEST_DIRECTORY)

include(${BOOST_DIR}/cmake/IncludeBoost.cmake)
