set(RTT_ANALYZER_SOURCE_DIRECTORY ${RTT_ANALYZER_DIR}/src)

set(RTT_ANALYZER_TEST_DIRECTORY ${RTT_ANALYZER_DIR}/tst)

set(RTT_ANALYZER_INCLUDE_DIRECTORIES ${RTT_ANALYZER_SOURCE_DIRECTORY})

set(RTT_ANALYZER_TEST_INCLUDE_DIRECTORIES ${RTT_ANALYZER_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${RTT_ANALYZER_SOURCE_DIRECTORY}]")
get_source_files_from_directory(RTT_ANALYZER_SOURCES ${RTT_ANALYZER_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${RTT_ANALYZER_TEST_DIRECTORY}]")
get_source_files_from_directory(RTT_ANALYZER_TESTS ${RTT_ANALYZER_TEST_DIRECTORY})

set(RTT_ANALYZER_SOURCES_AND_TESTS ${RTT_ANALYZER_SOURCES} ${RTT_ANALYZER_TESTS})
