/** @file
*   @brief Contains ERadDomain enum
*   @copyright 2018, 2019 Nokia. All rights reserved.
*/

#ifndef CCS_ERAD_DOMAIN_H
#define CCS_ERAD_DOMAIN_H

/**
 * @brief Enumeration for R&D domains
 */
typedef enum ERadDomain
{
    ERadDomain_Legacy              = 0,
    ERadDomain_Ccs                 = 1,
    ERadDomain_HwApi               = 2,
    ERadDomain_Dft                 = 3,
    ERadDomain_Telecom             = 4,
    ERadDomain_TUP                 = 5,
    ERadDomain_DSPCodec            = 6,
    ERadDomain_DSPRake             = 7,
    ERadDomain_DSPMac_hs           = 8,
    ERadDomain_DSPHsupaL2          = 9,
    ERadDomain_LteMac              = 10,
    ERadDomain_LteMacUl            = 11,
    ERadDomain_LteMacDl            = 12,
    ERadDomain_LteTupUl            = 13,
    ERadDomain_LteTupDl            = 14,
    ERadDomain_LteCellC            = 15,
    ERadDomain_LteCommon           = 16,
    ERadDomain_LteEnbc             = 17,
    ERadDomain_LteRrom             = 18,
    ERadDomain_LteUec              = 19,
    ERadDomain_LteLom              = 20,
    ERadDomain_LteTupC             = 21,
    ERadDomain_LteUlPhy            = 22,
    ERadDomain_LteDlPhy            = 23,
    ERadDomain_LteSmc              = 24,
    ERadDomain_Oam                 = 25,
    ERadDomain_Trs                 = 26,
    ERadDomain_DspHwApi            = 27,
    ERadDomain_Lom                 = 28,
    ERadDomain_LteMacTddPs         = 29,
    ERadDomain_LteMacFddPs         = 30,
    ERadDomain_LteMacDcmPs         = 31,
    ERadDomain_LteMacPsCommon      = 32,
    ERadDomain_BM                  = 33,
    ERadDomain_HwApiState          = 34,
    ERadDomain_ExtLogging          = 35,
    ERadDomain_DspLtcom            = 36,
    ERadDomain_DspMm               = 37,
    ERadDomain_DspRakeDch          = 38,
    ERadDomain_DspRakeRach         = 39,
    ERadDomain_DspFp               = 40,
    ERadDomain_DspHsTup            = 41,
    ERadDomain_DspPic              = 42,
    ERadDomain_DspW1PLRx           = 43,
    ERadDomain_DspW1PLTx           = 44,
    ERadDomain_TupC                = 45,
    ERadDomain_HwApiOmIface        = 46,
    ERadDomain_LIM                 = 47,
    ERadDomain_LteCellP            = 48,
    ERadDomain_LteFaReCo           = 49,
    ERadDomain_LteSysAdapter       = 50,
    ERadDomain_LteMOAM             = 51,
    ERadDomain_LteBSTAT            = 52,
    ERadDomain_Rfsw                = 53,
    ERadDomain_SWIM                = 54,
    ERadDomain_TddCpri             = 55,
    ERadDomain_LteMcec             = 56,
    ERadDomain_RtHwApi             = 57,
    ERadDomain_InfoModelGw         = 58,
    ERadDomain_FjRhPhy             = 59,
    ERadDomain_UpHwApi             = 60,
    ERadDomain_LteEnbson           = 61,
    ERadDomain_LteCellson          = 62,
    ERadDomain_CcsMcu              = 63,
    ERadDomain_EmServices          = 64,
    ERadDomain_LteTupCommon        = 65,
    ERadDomain_LteDCS              = 66,
    ERadDomain_LteMCTRL            = 67,
    ERadDomain_PhyProxy            = 68,
    ERadDomain_OamUri              = 69,
    ERadDomain_OamCci              = 70,
    ERadDomain_OamMci              = 71,
    ERadDomain_OamDem              = 72,
    ERadDomain_OamCem              = 73,
    ERadDomain_OamRem              = 74,
    ERadDomain_OamSwm              = 75,
    ERadDomain_OamCas              = 76,
    ERadDomain_OamLts              = 77,
    ERadDomain_OamGts              = 78,
    ERadDomain_OamHas              = 79,
    ERadDomain_OamFri              = 80,
    ERadDomain_OamSds              = 81,
    ERadDomain_OamTas              = 82,
    ERadDomain_OamWts              = 83,
    ERadDomain_LteSasProxy         = 84,
    ERadDomain_OamInct             = 85,
    ERadDomain_LteL1Low            = 86,
    ERadDomain_5GL2LO              = 87,
    ERadDomain_5GL2PS              = 88,
    ERadDomain_5GCPRT              = 89,
    ERadDomain_5GL2HiCu            = 90,
    ERadDomain_5GL2HiDu            = 91,
    ERadDomain_5GAirphone          = 92,
    ERadDomain_NodeOAM             = 93,
    ERadDomain_RACOAM              = 94,
    ERadDomain_SiteOAM             = 95,
    ERadDomain_OamNrts             = 96,
    ERadDomain_OamNe3sAdapter      = 97,
    ERadDomain_SMALiteXoh          = 98,
    ERadDomain_SMALiteFileTransfer = 99,
    ERadDomain_5GCpuDataCollector  = 100,
    ERadDomain_DSPGsm              = 101,
    ERadDomain_5GCPNRT             = 102,
    ERadDomain_CRM                 = 103,
    ERadDomain_DspSlaveRach        = 104
} ERadDomain;

#endif /* CCS_ERAD_DOMAIN_H */

