set(ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY
    ${ZZZ_MANIPULATE_FILES_DIR}/src
)

set(ZZZ_MANIPULATE_FILES_TEST_DIRECTORY
    ${ZZZ_MANIPULATE_FILES_DIR}/tst
)

set(ZZZ_MANIPULATE_FILES_INCLUDE_DIRECTORIES
    ${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY}
)

set(ZZZ_MANIPULATE_FILES_TEST_INCLUDE_DIRECTORIES
    ${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(ZZZ_MANIPULATE_FILES_SOURCES ${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(ZZZ_MANIPULATE_FILES_TESTS ${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY})

set(ZZZ_MANIPULATE_FILES_SOURCES_AND_TESTS
    ${ZZZ_MANIPULATE_FILES_SOURCES}
    ${ZZZ_MANIPULATE_FILES_TESTS}
)
