set(ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY ${ZZZ_MANIPULATE_FILES_DIR}/src)

set(ZZZ_MANIPULATE_FILES_TEST_DIRECTORY ${ZZZ_MANIPULATE_FILES_DIR}/tst)

set(ZZZ_MANIPULATE_FILES_INCLUDE_DIRECTORIES ${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY})

set(ZZZ_MANIPULATE_FILES_TEST_INCLUDE_DIRECTORIES ${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(ZZZ_MANIPULATE_FILES_SOURCES ${ZZZ_MANIPULATE_FILES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY}]")
get_source_files_from_directory(ZZZ_MANIPULATE_FILES_TESTS ${ZZZ_MANIPULATE_FILES_TEST_DIRECTORY})

set(ZZZ_MANIPULATE_FILES_SOURCES_AND_TESTS ${ZZZ_MANIPULATE_FILES_SOURCES} ${ZZZ_MANIPULATE_FILES_TESTS})
