set(APRG_COMMON_SOURCE_DIRECTORY
    ${APRG_COMMON_DIR}/src
)

set(APRG_COMMON_TEST_DIRECTORY
    ${APRG_COMMON_DIR}/tst
)

set(APRG_COMMON_WINDOWS_SOURCE_DIRECTORY
    ${APRG_COMMON_DIR}/srcWindows
)

set(APRG_COMMON_WINDOWS_TEST_DIRECTORY
    ${APRG_COMMON_DIR}/tstWindows
)

set(APRG_COMMON_LINUX_SOURCE_DIRECTORY
    ${APRG_COMMON_DIR}/srcLinux
)

set(APRG_COMMON_LINUX_TEST_DIRECTORY
    ${APRG_COMMON_DIR}/tstLinux
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${APRG_COMMON_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_SOURCES APRG_COMMON_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${APRG_COMMON_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_TESTS APRG_COMMON_TEST_DIRECTORY)

if(WIN32)
    PRINT_STATUS("Looking for Windows SRC C/C++ files in: [${APRG_COMMON_WINDOWS_SOURCE_DIRECTORY}]")
    GET_SUB_DIRECTORY_LIST(APRG_COMMON_WINDOWS_SOURCE_DIRECTORY_LIST ${APRG_COMMON_WINDOWS_SOURCE_DIRECTORY})
    GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_WINDOWS_SOURCES APRG_COMMON_WINDOWS_SOURCE_DIRECTORY)

    PRINT_STATUS("Looking for Windows TST C/C++ files in: [${APRG_COMMON_WINDOWS_TEST_DIRECTORY}]")
    GET_SUB_DIRECTORY_LIST(APRG_COMMON_WINDOWS_TEST_DIRECTORY_LIST ${APRG_COMMON_WINDOWS_TEST_DIRECTORY})
    GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_WINDOWS_TESTS APRG_COMMON_WINDOWS_TEST_DIRECTORY)

    set(APRG_COMMON_SOURCES ${APRG_COMMON_SOURCES} ${APRG_COMMON_WINDOWS_SOURCES} )
    set(APRG_COMMON_TESTS ${APRG_COMMON_TESTS} ${APRG_COMMON_WINDOWS_TESTS} )
    set(APRG_COMMON_INCLUDE_DIRECTORIES ${APRG_COMMON_SOURCE_DIRECTORY} ${APRG_COMMON_WINDOWS_SOURCE_DIRECTORY} )
    set(APRG_COMMON_TEST_INCLUDE_DIRECTORIES ${APRG_COMMON_TEST_DIRECTORY} ${APRG_COMMON_WINDOWS_TEST_DIRECTORY} )
elseif(UNIX)
    PRINT_STATUS("Looking for Linux SRC C/C++ files in: [${APRG_COMMON_LINUX_SOURCE_DIRECTORY}]")
    GET_SUB_DIRECTORY_LIST(APRG_COMMON_LINUX_SOURCE_DIRECTORY_LIST ${APRG_COMMON_LINUX_SOURCE_DIRECTORY})
    GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_LINUX_SOURCES APRG_COMMON_LINUX_SOURCE_DIRECTORY)

    PRINT_STATUS("Looking for Linux TST C/C++ files in: [${APRG_COMMON_LINUX_TEST_DIRECTORY}]")
    GET_SUB_DIRECTORY_LIST(APRG_COMMON_LINUX_TEST_DIRECTORY_LIST ${APRG_COMMON_LINUX_TEST_DIRECTORY})
    GET_SOURCE_FILES_FROM_DIRECTORY(APRG_COMMON_LINUX_TESTS APRG_COMMON_LINUX_TEST_DIRECTORY)

    set(APRG_COMMON_SOURCES ${APRG_COMMON_SOURCES} ${APRG_COMMON_LINUX_SOURCES} )
    set(APRG_COMMON_TESTS ${APRG_COMMON_TESTS} ${APRG_COMMON_LINUX_TESTS} )
    set(APRG_COMMON_INCLUDE_DIRECTORIES ${APRG_COMMON_SOURCE_DIRECTORY}  ${APRG_COMMON_LINUX_SOURCE_DIRECTORY} )
    set(APRG_COMMON_TEST_INCLUDE_DIRECTORIES ${APRG_COMMON_TEST_DIRECTORY} ${APRG_COMMON_LINUX_TEST_DIRECTORY} )
endif()

set(APRG_COMMON_SOURCES_AND_TESTS
    ${APRG_COMMON_SOURCES}
    ${APRG_COMMON_TESTS}
)
