# Process files for static_analyzers and beautifier

if (APRG_ENABLE_STATIC_ANALYZERS OR APRG_ENABLE_BEAUTIFIER)
    set(APRG_SOURCES_TO_PROCESS "${APRG_COMMON_SOURCES_AND_TESTS}")
    set(APRG_INCLUDES_DIRECTORIES_TO_PROCESS "${APRG_COMMON_INCLUDE_DIRECTORIES};${APRG_COMMON_TEST_INCLUDE_DIRECTORIES};${GTEST_INCLUDE_DIRECTORIES}")
    APRG_PROCESS_SOURCES("${APRG_SOURCES_TO_PROCESS}" "${APRG_INCLUDES_DIRECTORIES_TO_PROCESS}")
endif()
