set(MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY ${MESSAGE_CONTENT_CHECKER_DIR}/src)

set(MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY ${MESSAGE_CONTENT_CHECKER_DIR}/tst)

set(MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY ${MESSAGE_CONTENT_CHECKER_DIR}/main)

set(MESSAGE_CONTENT_CHECKER_INCLUDE_DIRECTORIES ${MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY})

set(MESSAGE_CONTENT_CHECKER_TEST_INCLUDE_DIRECTORIES ${MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY}]")
get_source_files_from_directory(MESSAGE_CONTENT_CHECKER_SOURCES ${MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY}]")
get_source_files_from_directory(MESSAGE_CONTENT_CHECKER_TESTS ${MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY}]")
get_source_files_from_directory(MESSAGE_CONTENT_CHECKER_MAIN_SOURCES ${MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY})

set(MESSAGE_CONTENT_CHECKER_SOURCES_AND_TESTS ${MESSAGE_CONTENT_CHECKER_SOURCES} ${MESSAGE_CONTENT_CHECKER_TESTS})
