set(MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY
    ${MESSAGE_CONTENT_CHECKER_DIR}/src
)

set(MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY
    ${MESSAGE_CONTENT_CHECKER_DIR}/tst
)

set(MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY
    ${MESSAGE_CONTENT_CHECKER_DIR}/main
)

set(MESSAGE_CONTENT_CHECKER_INCLUDE_DIRECTORIES
    ${MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY}
)

set(MESSAGE_CONTENT_CHECKER_TEST_INCLUDE_DIRECTORIES
    ${MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(MESSAGE_CONTENT_CHECKER_SOURCES MESSAGE_CONTENT_CHECKER_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(MESSAGE_CONTENT_CHECKER_TESTS MESSAGE_CONTENT_CHECKER_TEST_DIRECTORY)

PRINT_STATUS("Looking for MAIN C/C++ files in: [${MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(MESSAGE_CONTENT_CHECKER_MAIN_SOURCES MESSAGE_CONTENT_CHECKER_MAIN_DIRECTORY)

set(MESSAGE_CONTENT_CHECKER_SOURCES_AND_TESTS
    ${MESSAGE_CONTENT_CHECKER_SOURCES}
    ${MESSAGE_CONTENT_CHECKER_TESTS}
)
