set(APRG_GSL_SOURCE_DIRECTORY ${APRG_GSL_DIR}/src)

set(APRG_GSL_TEST_DIRECTORY ${APRG_GSL_DIR}/tst)

set(APRG_GSL_INCLUDE_DIRECTORIES ${APRG_GSL_SOURCE_DIRECTORY})

set(APRG_GSL_TEST_INCLUDE_DIRECTORIES ${APRG_GSL_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_GSL_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_GSL_SOURCES ${APRG_GSL_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_GSL_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_GSL_TESTS ${APRG_GSL_TEST_DIRECTORY})

set(APRG_GSL_SOURCES_AND_TESTS ${APRG_GSL_SOURCES} ${APRG_GSL_TESTS})
