set(SNAPSHOT_DETAILS_SOURCE_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/src
)

set(SNAPSHOT_DETAILS_TEST_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/tst
)

set(SNAPSHOT_DETAILS_MAIN_DIRECTORY
    ${SNAPSHOT_DETAILS_DIR}/main
)

set(SNAPSHOT_DETAILS_INCLUDE_DIRECTORIES
    ${SNAPSHOT_DETAILS_SOURCE_DIRECTORY}
)

set(SNAPSHOT_DETAILS_TEST_INCLUDE_DIRECTORIES
    ${SNAPSHOT_DETAILS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${SNAPSHOT_DETAILS_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SNAPSHOT_DETAILS_SOURCES ${SNAPSHOT_DETAILS_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${SNAPSHOT_DETAILS_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SNAPSHOT_DETAILS_TESTS ${SNAPSHOT_DETAILS_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${SNAPSHOT_DETAILS_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SNAPSHOT_DETAILS_MAIN_SOURCES ${SNAPSHOT_DETAILS_MAIN_DIRECTORY})

set(SNAPSHOT_DETAILS_SOURCES_AND_TESTS
    ${SNAPSHOT_DETAILS_SOURCES}
    ${SNAPSHOT_DETAILS_TESTS}
)
