/**
********************************************************************************
* @file                  $HeadURL: https://wrscmi.inside.nsn.com/isource/svnroot/BTS_I_WN/tags/WBTS00_ENV_1910_001_00/I_Interface/Application_Env/Wn_Env/Bs_Env/Definitions/TBitRate.h $
* @version               $LastChangedRevision: 4479 $
* @date                  $LastChangedDate: 2014-12-02 15:49:36 +0800 (Tue, 02 Dec 2014) $
* @author                $Author: rwojtyna $
*
* Original author 
*
* @brief THIS FILE HAS BEEN GENERATED BY ISAR
*
* Copyright 2014 Nokia. All rights reserved.
*******************************************************************************/

#ifndef _TBIT_RATE_H
#define _TBIT_RATE_H

#include <glo_def.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef u32 TBitRate;


void FCtConvertTBitRate(TBitRate * pld, u32 len, TBoolean isInSendMode);

#ifdef __cplusplus
}
#endif

#endif /* _TBIT_RATE_H */

/**
********************************************************************************
* @typedef TBitRate
*
* Description : no description provided for this typedef
*
*
*
* Definition Provided By : The TrswSetup System Component
*
* Remember to put an empty line in the end of each definition file.
* Otherwise the compiler will generate a warning.
*******************************************************************************/

