set(BTS_TRACE_DECODER_SOURCE_DIRECTORY ${BTS_TRACE_DECODER_DIR}/src)

set(BTS_TRACE_DECODER_TEST_DIRECTORY ${BTS_TRACE_DECODER_DIR}/tst)

set(BTS_TRACE_DECODER_MAIN_DIRECTORY ${BTS_TRACE_DECODER_DIR}/main)

set(BTS_TRACE_DECODER_INCLUDE_DIRECTORIES ${BTS_TRACE_DECODER_SOURCE_DIRECTORY})

set(BTS_TRACE_DECODER_TEST_INCLUDE_DIRECTORIES ${BTS_TRACE_DECODER_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${BTS_TRACE_DECODER_SOURCE_DIRECTORY}]")
get_source_files_from_directory(BTS_TRACE_DECODER_SOURCES ${BTS_TRACE_DECODER_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${BTS_TRACE_DECODER_TEST_DIRECTORY}]")
get_source_files_from_directory(BTS_TRACE_DECODER_TESTS ${BTS_TRACE_DECODER_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${BTS_TRACE_DECODER_MAIN_DIRECTORY}]")
get_source_files_from_directory(BTS_TRACE_DECODER_MAIN_SOURCES ${BTS_TRACE_DECODER_MAIN_DIRECTORY})

set(BTS_TRACE_DECODER_SOURCES_AND_TESTS ${BTS_TRACE_DECODER_SOURCES} ${BTS_TRACE_DECODER_TESTS})
