set(CRNCCID_MAPPING_SOURCE_DIRECTORY ${CRNCCID_MAPPING_DIR}/src)

set(CRNCCID_MAPPING_TEST_DIRECTORY ${CRNCCID_MAPPING_DIR}/tst)

set(CRNCCID_MAPPING_INCLUDE_DIRECTORIES ${CRNCCID_MAPPING_SOURCE_DIRECTORY})

set(CRNCCID_MAPPING_TEST_INCLUDE_DIRECTORIES ${CRNCCID_MAPPING_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${CRNCCID_MAPPING_SOURCE_DIRECTORY}]")
get_source_files_from_directory(CRNCCID_MAPPING_SOURCES ${CRNCCID_MAPPING_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${CRNCCID_MAPPING_TEST_DIRECTORY}]")
get_source_files_from_directory(CRNCCID_MAPPING_TESTS ${CRNCCID_MAPPING_TEST_DIRECTORY})

set(CRNCCID_MAPPING_SOURCES_AND_TESTS ${CRNCCID_MAPPING_SOURCES} ${CRNCCID_MAPPING_TESTS})
