version: 2

python:
  version: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: ampl/doc/conf.py

python:
   install:
   - requirements: ampl/doc/requirements.txt