set(APRG_MODELLING_SOURCE_DIRECTORY ${APRG_MODELLING_DIR}/src)

set(APRG_MODELLING_TEST_DIRECTORY ${APRG_MODELLING_DIR}/tst)

set(APRG_MODELLING_INCLUDE_DIRECTORIES ${APRG_MODELLING_SOURCE_DIRECTORY})

set(APRG_MODELLING_TEST_INCLUDE_DIRECTORIES ${APRG_MODELLING_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_MODELLING_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_MODELLING_SOURCES ${APRG_MODELLING_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_MODELLING_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_MODELLING_TESTS ${APRG_MODELLING_TEST_DIRECTORY})

set(APRG_MODELLING_SOURCES_AND_TESTS ${APRG_MODELLING_SOURCES} ${APRG_MODELLING_TESTS})
