set(APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY ${APRG_FILE_EXTRACTOR_DIR}/src)

set(APRG_FILE_EXTRACTOR_TEST_DIRECTORY ${APRG_FILE_EXTRACTOR_DIR}/tst)

set(APRG_FILE_EXTRACTOR_MAIN_DIRECTORY ${APRG_FILE_EXTRACTOR_DIR}/main)

set(APRG_FILE_EXTRACTOR_INCLUDE_DIRECTORIES ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY})

set(APRG_FILE_EXTRACTOR_TEST_INCLUDE_DIRECTORIES ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_FILE_EXTRACTOR_SOURCES ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_FILE_EXTRACTOR_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_FILE_EXTRACTOR_TESTS ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY}]")
get_source_files_from_directory(APRG_FILE_EXTRACTOR_MAIN_SOURCES ${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY})

set(APRG_FILE_EXTRACTOR_SOURCES_AND_TESTS ${APRG_FILE_EXTRACTOR_SOURCES} ${APRG_FILE_EXTRACTOR_TESTS})
