set(APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/src
)

set(APRG_FILE_EXTRACTOR_TEST_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/tst
)

set(APRG_FILE_EXTRACTOR_MAIN_DIRECTORY
    ${APRG_FILE_EXTRACTOR_DIR}/main
)

set(APRG_FILE_EXTRACTOR_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY}
)

set(APRG_FILE_EXTRACTOR_TEST_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_FILE_EXTRACTOR_SOURCES ${APRG_FILE_EXTRACTOR_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${APRG_FILE_EXTRACTOR_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_FILE_EXTRACTOR_TESTS ${APRG_FILE_EXTRACTOR_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_FILE_EXTRACTOR_MAIN_SOURCES ${APRG_FILE_EXTRACTOR_MAIN_DIRECTORY})

set(APRG_FILE_EXTRACTOR_SOURCES_AND_TESTS
    ${APRG_FILE_EXTRACTOR_SOURCES}
    ${APRG_FILE_EXTRACTOR_TESTS}
)
