set(REVISION_EDITOR_SOURCE_DIRECTORY ${REVISION_EDITOR_DIR}/src)

set(REVISION_EDITOR_TEST_DIRECTORY ${REVISION_EDITOR_DIR}/tst)

set(REVISION_EDITOR_MAIN_DIRECTORY ${REVISION_EDITOR_DIR}/main)

set(REVISION_EDITOR_INCLUDE_DIRECTORIES ${REVISION_EDITOR_SOURCE_DIRECTORY})

set(REVISION_EDITOR_TEST_INCLUDE_DIRECTORIES ${REVISION_EDITOR_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${REVISION_EDITOR_SOURCE_DIRECTORY}]")
get_source_files_from_directory(REVISION_EDITOR_SOURCES ${REVISION_EDITOR_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${REVISION_EDITOR_TEST_DIRECTORY}]")
get_source_files_from_directory(REVISION_EDITOR_TESTS ${REVISION_EDITOR_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${REVISION_EDITOR_MAIN_DIRECTORY}]")
get_source_files_from_directory(REVISION_EDITOR_MAIN_SOURCES ${REVISION_EDITOR_MAIN_DIRECTORY})

set(REVISION_EDITOR_SOURCES_AND_TESTS ${REVISION_EDITOR_SOURCES} ${REVISION_EDITOR_TESTS})
