set(REVISION_EDITOR_SOURCE_DIRECTORY
    ${REVISION_EDITOR_DIR}/src
)

set(REVISION_EDITOR_TEST_DIRECTORY
    ${REVISION_EDITOR_DIR}/tst
)

set(REVISION_EDITOR_MAIN_DIRECTORY
    ${REVISION_EDITOR_DIR}/main
)

set(REVISION_EDITOR_INCLUDE_DIRECTORIES
    ${REVISION_EDITOR_SOURCE_DIRECTORY}
)

set(REVISION_EDITOR_TEST_INCLUDE_DIRECTORIES
    ${REVISION_EDITOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${REVISION_EDITOR_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(REVISION_EDITOR_SOURCES REVISION_EDITOR_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${REVISION_EDITOR_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(REVISION_EDITOR_TESTS REVISION_EDITOR_TEST_DIRECTORY)

PRINT_STATUS("Looking for MAIN C/C++ files in: [${REVISION_EDITOR_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(REVISION_EDITOR_MAIN_SOURCES REVISION_EDITOR_MAIN_DIRECTORY)

set(REVISION_EDITOR_SOURCES_AND_TESTS
    ${REVISION_EDITOR_SOURCES}
    ${REVISION_EDITOR_TESTS}
)
