set(APRG_GEOMETRY_SOURCE_DIRECTORY ${APRG_GEOMETRY_DIR}/src)

set(APRG_GEOMETRY_TEST_DIRECTORY ${APRG_GEOMETRY_DIR}/tst)

set(APRG_GEOMETRY_INCLUDE_DIRECTORIES ${APRG_GEOMETRY_SOURCE_DIRECTORY})

set(APRG_GEOMETRY_TEST_INCLUDE_DIRECTORIES ${APRG_GEOMETRY_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_GEOMETRY_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_GEOMETRY_SOURCES ${APRG_GEOMETRY_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_GEOMETRY_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_GEOMETRY_TESTS ${APRG_GEOMETRY_TEST_DIRECTORY})

set(APRG_GEOMETRY_SOURCES_AND_TESTS ${APRG_GEOMETRY_SOURCES} ${APRG_GEOMETRY_TESTS})
