set(QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY
    ${QUICKEST_WAY_TO_PROGRAM_DIR}/src
)

set(QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY
    ${QUICKEST_WAY_TO_PROGRAM_DIR}/tst
)

set(QUICKEST_WAY_TO_PROGRAM_INCLUDE_DIRECTORIES
    ${QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY}
)

set(QUICKEST_WAY_TO_PROGRAM_TEST_INCLUDE_DIRECTORIES
    ${QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(QUICKEST_WAY_TO_PROGRAM_SOURCES QUICKEST_WAY_TO_PROGRAM_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(QUICKEST_WAY_TO_PROGRAM_TESTS QUICKEST_WAY_TO_PROGRAM_TEST_DIRECTORY)

set(QUICKEST_WAY_TO_PROGRAM_SOURCES_AND_TESTS
    ${QUICKEST_WAY_TO_PROGRAM_SOURCES}
    ${QUICKEST_WAY_TO_PROGRAM_TESTS}
)
