set(BTS_LOG_ANALYZER_SOURCE_DIRECTORY ${BTS_LOG_ANALYZER_DIR}/src)

set(BTS_LOG_ANALYZER_TEST_DIRECTORY ${BTS_LOG_ANALYZER_DIR}/tst)

set(BTS_LOG_ANALYZER_INCLUDE_DIRECTORIES ${BTS_LOG_ANALYZER_SOURCE_DIRECTORY})

set(BTS_LOG_ANALYZER_TEST_INCLUDE_DIRECTORIES ${BTS_LOG_ANALYZER_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${BTS_LOG_ANALYZER_SOURCE_DIRECTORY}]")
get_source_files_from_directory(BTS_LOG_ANALYZER_SOURCES ${BTS_LOG_ANALYZER_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${BTS_LOG_ANALYZER_TEST_DIRECTORY}]")
get_source_files_from_directory(BTS_LOG_ANALYZER_TESTS ${BTS_LOG_ANALYZER_TEST_DIRECTORY})

set(BTS_LOG_ANALYZER_SOURCES_AND_TESTS ${BTS_LOG_ANALYZER_SOURCES} ${BTS_LOG_ANALYZER_TESTS})
