set(APRG_STATISTICS_SOURCE_DIRECTORY ${APRG_STATISTICS_DIR}/src)

set(APRG_STATISTICS_TEST_DIRECTORY ${APRG_STATISTICS_DIR}/tst)

set(APRG_STATISTICS_INCLUDE_DIRECTORIES ${APRG_STATISTICS_SOURCE_DIRECTORY})

set(APRG_STATISTICS_TEST_INCLUDE_DIRECTORIES ${APRG_STATISTICS_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_STATISTICS_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_STATISTICS_SOURCES ${APRG_STATISTICS_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_STATISTICS_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_STATISTICS_TESTS ${APRG_STATISTICS_TEST_DIRECTORY})

set(APRG_STATISTICS_SOURCES_AND_TESTS ${APRG_STATISTICS_SOURCES} ${APRG_STATISTICS_TESTS})
