set(CHESS_UTILITIES_SOURCE_DIRECTORY ${CHESS_UTILITIES_DIR}/src)

set(CHESS_UTILITIES_TEST_DIRECTORY ${CHESS_UTILITIES_DIR}/tst)

set(CHESS_UTILITIES_MAIN_DIRECTORY ${CHESS_UTILITIES_DIR}/main)

set(CHESS_UTILITIES_INCLUDE_DIRECTORIES ${CHESS_UTILITIES_SOURCE_DIRECTORY})

set(CHESS_UTILITIES_TEST_INCLUDE_DIRECTORIES ${CHESS_UTILITIES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${CHESS_UTILITIES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(CHESS_UTILITIES_SOURCES ${CHESS_UTILITIES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${CHESS_UTILITIES_TEST_DIRECTORY}]")
get_source_files_from_directory(CHESS_UTILITIES_TESTS ${CHESS_UTILITIES_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${CHESS_UTILITIES_MAIN_DIRECTORY}]")
get_source_files_from_directory(CHESS_UTILITIES_MAIN_SOURCES ${CHESS_UTILITIES_MAIN_DIRECTORY})

set(CHESS_UTILITIES_SOURCES_AND_TESTS ${CHESS_UTILITIES_SOURCES} ${CHESS_UTILITIES_TESTS})
