set(RAGNAROK_ONLINE_SOURCE_DIRECTORY
    ${RAGNAROK_ONLINE_DIR}/src
)

set(RAGNAROK_ONLINE_TEST_DIRECTORY
    ${RAGNAROK_ONLINE_DIR}/tst
)

set(RAGNAROK_ONLINE_MAIN_DIRECTORY
    ${RAGNAROK_ONLINE_DIR}/main
)

set(RAGNAROK_ONLINE_INCLUDE_DIRECTORIES
    ${RAGNAROK_ONLINE_SOURCE_DIRECTORY}
)

set(RAGNAROK_ONLINE_TEST_INCLUDE_DIRECTORIES
    ${RAGNAROK_ONLINE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${RAGNAROK_ONLINE_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(RAGNAROK_ONLINE_SOURCES RAGNAROK_ONLINE_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${RAGNAROK_ONLINE_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(RAGNAROK_ONLINE_TESTS RAGNAROK_ONLINE_TEST_DIRECTORY)

PRINT_STATUS("Looking for MAIN C/C++ files in: [${RAGNAROK_ONLINE_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(RAGNAROK_ONLINE_MAIN_SOURCES RAGNAROK_ONLINE_MAIN_DIRECTORY)

set(RAGNAROK_ONLINE_SOURCES_AND_TESTS
    ${RAGNAROK_ONLINE_SOURCES}
    ${RAGNAROK_ONLINE_TESTS}
)
