set(TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY
    ${TEMPLATE_FOR_LIBRARIES_DIR}/src
)

set(TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY
    ${TEMPLATE_FOR_LIBRARIES_DIR}/tst
)

set(TEMPLATE_FOR_LIBRARIES_INCLUDE_DIRECTORIES
    ${TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY}
)

set(TEMPLATE_FOR_LIBRARIES_TEST_INCLUDE_DIRECTORIES
    ${TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(TEMPLATE_FOR_LIBRARIES_SOURCES TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(TEMPLATE_FOR_LIBRARIES_TESTS TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY)

set(TEMPLATE_FOR_LIBRARIES_SOURCES_AND_TESTS
    ${TEMPLATE_FOR_LIBRARIES_SOURCES}
    ${TEMPLATE_FOR_LIBRARIES_TESTS}
)
