set(TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY ${TEMPLATE_FOR_LIBRARIES_DIR}/src)

set(TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY ${TEMPLATE_FOR_LIBRARIES_DIR}/tst)

set(TEMPLATE_FOR_LIBRARIES_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY})

set(TEMPLATE_FOR_LIBRARIES_TEST_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_LIBRARIES_SOURCES ${TEMPLATE_FOR_LIBRARIES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_LIBRARIES_TESTS ${TEMPLATE_FOR_LIBRARIES_TEST_DIRECTORY})

set(TEMPLATE_FOR_LIBRARIES_SOURCES_AND_TESTS ${TEMPLATE_FOR_LIBRARIES_SOURCES} ${TEMPLATE_FOR_LIBRARIES_TESTS})
