set(CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY
    ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/src
)

set(CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY
    ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/tst
)

set(CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY
    ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/main
)

set(CONVERT_PLMNID_TO_MCC_MNC_INCLUDE_DIRECTORIES
    ${CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY}
)

set(CONVERT_PLMNID_TO_MCC_MNC_TEST_INCLUDE_DIRECTORIES
    ${CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CONVERT_PLMNID_TO_MCC_MNC_SOURCES CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CONVERT_PLMNID_TO_MCC_MNC_TESTS CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY)

PRINT_STATUS("Looking for MAIN C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CONVERT_PLMNID_TO_MCC_MNC_MAIN_SOURCES CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY)

set(CONVERT_PLMNID_TO_MCC_MNC_SOURCES_AND_TESTS
    ${CONVERT_PLMNID_TO_MCC_MNC_SOURCES}
    ${CONVERT_PLMNID_TO_MCC_MNC_TESTS}
)
