set(CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/src)

set(CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/tst)

set(CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY ${CONVERT_PLMNID_TO_MCC_MNC_DIR}/main)

set(CONVERT_PLMNID_TO_MCC_MNC_INCLUDE_DIRECTORIES ${CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY})

set(CONVERT_PLMNID_TO_MCC_MNC_TEST_INCLUDE_DIRECTORIES ${CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY}]")
get_source_files_from_directory(CONVERT_PLMNID_TO_MCC_MNC_SOURCES ${CONVERT_PLMNID_TO_MCC_MNC_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY}]")
get_source_files_from_directory(CONVERT_PLMNID_TO_MCC_MNC_TESTS ${CONVERT_PLMNID_TO_MCC_MNC_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY}]")
get_source_files_from_directory(CONVERT_PLMNID_TO_MCC_MNC_MAIN_SOURCES ${CONVERT_PLMNID_TO_MCC_MNC_MAIN_DIRECTORY})

set(CONVERT_PLMNID_TO_MCC_MNC_SOURCES_AND_TESTS ${CONVERT_PLMNID_TO_MCC_MNC_SOURCES} ${CONVERT_PLMNID_TO_MCC_MNC_TESTS})
