set(DESIGN_PATTERNS_SOURCE_DIRECTORY
    ${DESIGN_PATTERNS_DIR}/src
)

set(DESIGN_PATTERNS_TEST_DIRECTORY
    ${DESIGN_PATTERNS_DIR}/tst
)

set(DESIGN_PATTERNS_INCLUDE_DIRECTORIES
    ${DESIGN_PATTERNS_SOURCE_DIRECTORY}
)

set(DESIGN_PATTERNS_TEST_INCLUDE_DIRECTORIES
    ${DESIGN_PATTERNS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${DESIGN_PATTERNS_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(DESIGN_PATTERNS_SOURCES DESIGN_PATTERNS_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${DESIGN_PATTERNS_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(DESIGN_PATTERNS_TESTS DESIGN_PATTERNS_TEST_DIRECTORY)

set(DESIGN_PATTERNS_SOURCES_AND_TESTS
    ${DESIGN_PATTERNS_SOURCES}
    ${DESIGN_PATTERNS_TESTS}
)
