set(DESIGN_PATTERNS_SOURCE_DIRECTORY ${DESIGN_PATTERNS_DIR}/src)

set(DESIGN_PATTERNS_TEST_DIRECTORY ${DESIGN_PATTERNS_DIR}/tst)

set(DESIGN_PATTERNS_INCLUDE_DIRECTORIES ${DESIGN_PATTERNS_SOURCE_DIRECTORY})

set(DESIGN_PATTERNS_TEST_INCLUDE_DIRECTORIES ${DESIGN_PATTERNS_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${DESIGN_PATTERNS_SOURCE_DIRECTORY}]")
get_source_files_from_directory(DESIGN_PATTERNS_SOURCES ${DESIGN_PATTERNS_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${DESIGN_PATTERNS_TEST_DIRECTORY}]")
get_source_files_from_directory(DESIGN_PATTERNS_TESTS ${DESIGN_PATTERNS_TEST_DIRECTORY})

set(DESIGN_PATTERNS_SOURCES_AND_TESTS ${DESIGN_PATTERNS_SOURCES} ${DESIGN_PATTERNS_TESTS})
