set(APRG_MATH_SOURCE_DIRECTORY ${APRG_MATH_DIR}/src)

set(APRG_MATH_TEST_DIRECTORY ${APRG_MATH_DIR}/tst)

set(APRG_MATH_INCLUDE_DIRECTORIES ${APRG_MATH_SOURCE_DIRECTORY})

set(APRG_MATH_TEST_INCLUDE_DIRECTORIES ${APRG_MATH_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_MATH_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_MATH_SOURCES ${APRG_MATH_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_MATH_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_MATH_TESTS ${APRG_MATH_TEST_DIRECTORY})

set(APRG_MATH_SOURCES_AND_TESTS ${APRG_MATH_SOURCES} ${APRG_MATH_TESTS})
