set(APRG_MATH_SOURCE_DIRECTORY
    ${APRG_MATH_DIR}/src
)

set(APRG_MATH_TEST_DIRECTORY
    ${APRG_MATH_DIR}/tst
)

set(APRG_MATH_INCLUDE_DIRECTORIES
    ${APRG_MATH_SOURCE_DIRECTORY}
)

set(APRG_MATH_TEST_INCLUDE_DIRECTORIES
    ${APRG_MATH_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${APRG_MATH_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_MATH_SOURCES ${APRG_MATH_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${APRG_MATH_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_MATH_TESTS ${APRG_MATH_TEST_DIRECTORY})

set(APRG_MATH_SOURCES_AND_TESTS
    ${APRG_MATH_SOURCES}
    ${APRG_MATH_TESTS}
)
