set(TDD_LECTURE_SOURCE_DIRECTORY ${TDD_LECTURE_DIR}/src)

set(TDD_LECTURE_TEST_DIRECTORY ${TDD_LECTURE_DIR}/tst)

set(TDD_LECTURE_MAIN_DIRECTORY ${TDD_LECTURE_DIR}/main)

set(TDD_LECTURE_INCLUDE_DIRECTORIES ${TDD_LECTURE_SOURCE_DIRECTORY})

set(TDD_LECTURE_TEST_INCLUDE_DIRECTORIES ${TDD_LECTURE_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${TDD_LECTURE_SOURCE_DIRECTORY}]")
get_source_files_from_directory(TDD_LECTURE_SOURCES ${TDD_LECTURE_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${TDD_LECTURE_TEST_DIRECTORY}]")
get_source_files_from_directory(TDD_LECTURE_TESTS ${TDD_LECTURE_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${TDD_LECTURE_MAIN_DIRECTORY}]")
get_source_files_from_directory(TDD_LECTURE_MAIN_SOURCES ${TDD_LECTURE_MAIN_DIRECTORY})

set(TDD_LECTURE_SOURCES_AND_TESTS ${TDD_LECTURE_SOURCES} ${TDD_LECTURE_TESTS})
