set(WCDMA_TOOLS_BACKEND_SOURCE_DIRECTORY ${WCDMA_TOOLS_BACKEND_DIR}/src)

set(WCDMA_TOOLS_BACKEND_TEST_DIRECTORY ${WCDMA_TOOLS_BACKEND_DIR}/tst)

set(WCDMA_TOOLS_BACKEND_INCLUDE_DIRECTORIES ${WCDMA_TOOLS_BACKEND_SOURCE_DIRECTORY})

set(WCDMA_TOOLS_BACKEND_TEST_INCLUDE_DIRECTORIES ${WCDMA_TOOLS_BACKEND_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${WCDMA_TOOLS_BACKEND_SOURCE_DIRECTORY}]")
get_source_files_from_directory(WCDMA_TOOLS_BACKEND_SOURCES ${WCDMA_TOOLS_BACKEND_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${WCDMA_TOOLS_BACKEND_TEST_DIRECTORY}]")
get_source_files_from_directory(WCDMA_TOOLS_BACKEND_TESTS ${WCDMA_TOOLS_BACKEND_TEST_DIRECTORY})

set(WCDMA_TOOLS_BACKEND_SOURCES_AND_TESTS ${WCDMA_TOOLS_BACKEND_SOURCES} ${WCDMA_TOOLS_BACKEND_TESTS})
