set(APRG_JSON_SOURCE_DIRECTORY ${APRG_JSON_DIR}/src)

set(APRG_JSON_TEST_DIRECTORY ${APRG_JSON_DIR}/tst)

set(APRG_JSON_INCLUDE_DIRECTORIES ${APRG_JSON_SOURCE_DIRECTORY})

set(APRG_JSON_TEST_INCLUDE_DIRECTORIES ${APRG_JSON_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_JSON_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_JSON_SOURCES ${APRG_JSON_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_JSON_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_JSON_TESTS ${APRG_JSON_TEST_DIRECTORY})

set(APRG_JSON_SOURCES_AND_TESTS ${APRG_JSON_SOURCES} ${APRG_JSON_TESTS})
