set(APRG_JSON_SOURCE_DIRECTORY
    ${APRG_JSON_DIR}/src
)

set(APRG_JSON_TEST_DIRECTORY
    ${APRG_JSON_DIR}/tst
)

set(APRG_JSON_INCLUDE_DIRECTORIES
    ${APRG_JSON_SOURCE_DIRECTORY}
)

set(APRG_JSON_TEST_INCLUDE_DIRECTORIES
    ${APRG_JSON_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${APRG_JSON_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_JSON_SOURCES ${APRG_JSON_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${APRG_JSON_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_JSON_TESTS ${APRG_JSON_TEST_DIRECTORY})

set(APRG_JSON_SOURCES_AND_TESTS
    ${APRG_JSON_SOURCES}
    ${APRG_JSON_TESTS}
)
