set(DD_CREATOR_COMMON_SOURCE_DIRECTORY ${DD_CREATOR_DIR}/src/Common/)

set(DD_CREATOR_COMMON_TEST_DIRECTORY ${DD_CREATOR_DIR}/tst/Common/)

print_status("Looking for sources C/C++ files in: [${DD_CREATOR_COMMON_SOURCE_DIRECTORY}]")
get_source_files_from_directory(DD_CREATOR_COMMON_SOURCES ${DD_CREATOR_COMMON_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${DD_CREATOR_COMMON_TEST_DIRECTORY}]")
get_source_files_from_directory(DD_CREATOR_COMMON_TESTS ${DD_CREATOR_COMMON_TEST_DIRECTORY})

set(DD_CREATOR_COMMON_SOURCES_AND_TESTS ${DD_CREATOR_COMMON_SOURCES} ${DD_CREATOR_COMMON_TESTS})
