set(FEATURE_SOURCE_DIRECTORY ${DD_CREATOR_DIR}/src/${FEATURE_FOLDER}/)

set(FEATURE_TEST_DIRECTORY ${DD_CREATOR_DIR}/tst/${FEATURE_FOLDER}/)

set(FEATURE_INCLUDE_DIRECTORIES ${FEATURE_SOURCE_DIRECTORY} ${FEATURE_TEST_DIRECTORY})

print_status("Looking for ${FEATURE_FOLDER} sources C/C++ files in: [${FEATURE_SOURCE_DIRECTORY}]")
get_source_files_from_directory(FEATURE_SOURCES ${FEATURE_SOURCE_DIRECTORY})

print_status("Looking for ${FEATURE_FOLDER} tests C/C++ files in: [${FEATURE_TEST_DIRECTORY}]")
get_source_files_from_directory(FEATURE_TESTS ${FEATURE_TEST_DIRECTORY})

set(FEATURE_SOURCES_AND_TESTS ${FEATURE_SOURCES} ${FEATURE_TESTS})
