set(FEATURE_SOURCE_DIRECTORY
    ${DD_CREATOR_DIR}/src/${FEATURE_FOLDER}/
)

set(FEATURE_TEST_DIRECTORY
    ${DD_CREATOR_DIR}/tst/${FEATURE_FOLDER}/
)

set(FEATURE_INCLUDE_DIRECTORIES
    ${FEATURE_SOURCE_DIRECTORY}
    ${FEATURE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for ${FEATURE_FOLDER} SRC C/C++ files in: [${FEATURE_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(FEATURE_SOURCES FEATURE_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for ${FEATURE_FOLDER} TST C/C++ files in: [${FEATURE_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(FEATURE_TESTS FEATURE_TEST_DIRECTORY)

set(FEATURE_SOURCES_AND_TESTS
    ${FEATURE_SOURCES}
    ${FEATURE_TESTS}
)

