set(SOOSA_SOURCE_DIRECTORY
    ${SOOSA_DIR}/src
)

set(SOOSA_TEST_DIRECTORY
    ${SOOSA_DIR}/tst
)

set(SOOSA_MAIN_DIRECTORY
    ${SOOSA_DIR}/main
)

set(SOOSA_INCLUDE_DIRECTORIES
    ${SOOSA_SOURCE_DIRECTORY}
)

set(SOOSA_TEST_INCLUDE_DIRECTORIES
    ${SOOSA_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${SOOSA_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SOOSA_SOURCES ${SOOSA_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${SOOSA_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SOOSA_TESTS ${SOOSA_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${SOOSA_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(SOOSA_MAIN_SOURCES ${SOOSA_MAIN_DIRECTORY})

set(SOOSA_SOURCES_AND_TESTS
    ${SOOSA_SOURCES}
    ${SOOSA_TESTS}
)
