set(APRG_CODE_UTILITIES_SOURCE_DIRECTORY ${APRG_CODE_UTILITIES_DIR}/src)

set(APRG_CODE_UTILITIES_TEST_DIRECTORY ${APRG_CODE_UTILITIES_DIR}/tst)

set(APRG_CODE_UTILITIES_MAIN_DIRECTORY ${APRG_CODE_UTILITIES_DIR}/main)

set(APRG_CODE_UTILITIES_INCLUDE_DIRECTORIES ${APRG_CODE_UTILITIES_SOURCE_DIRECTORY})

set(APRG_CODE_UTILITIES_TEST_INCLUDE_DIRECTORIES ${APRG_CODE_UTILITIES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_CODE_UTILITIES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_CODE_UTILITIES_SOURCES ${APRG_CODE_UTILITIES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_CODE_UTILITIES_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_CODE_UTILITIES_TESTS ${APRG_CODE_UTILITIES_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${APRG_CODE_UTILITIES_MAIN_DIRECTORY}]")
get_source_files_from_directory(APRG_CODE_UTILITIES_MAIN_SOURCES ${APRG_CODE_UTILITIES_MAIN_DIRECTORY})

set(APRG_CODE_UTILITIES_SOURCES_AND_TESTS ${APRG_CODE_UTILITIES_SOURCES} ${APRG_CODE_UTILITIES_TESTS})
