set(TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY
    ${TEMPLATE_FOR_PROGRAMS_DIR}/src
)

set(TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY
    ${TEMPLATE_FOR_PROGRAMS_DIR}/tst
)

set(TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY
    ${TEMPLATE_FOR_PROGRAMS_DIR}/main
)

set(TEMPLATE_FOR_PROGRAMS_INCLUDE_DIRECTORIES
    ${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY}
)

set(TEMPLATE_FOR_PROGRAMS_TEST_INCLUDE_DIRECTORIES
    ${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(TEMPLATE_FOR_PROGRAMS_SOURCES ${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(TEMPLATE_FOR_PROGRAMS_TESTS ${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(TEMPLATE_FOR_PROGRAMS_MAIN_SOURCES ${TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY})

set(TEMPLATE_FOR_PROGRAMS_SOURCES_AND_TESTS
    ${TEMPLATE_FOR_PROGRAMS_SOURCES}
    ${TEMPLATE_FOR_PROGRAMS_TESTS}
)
