set(TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY ${TEMPLATE_FOR_PROGRAMS_DIR}/src)

set(TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY ${TEMPLATE_FOR_PROGRAMS_DIR}/tst)

set(TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY ${TEMPLATE_FOR_PROGRAMS_DIR}/main)

set(TEMPLATE_FOR_PROGRAMS_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY})

set(TEMPLATE_FOR_PROGRAMS_TEST_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_PROGRAMS_SOURCES ${TEMPLATE_FOR_PROGRAMS_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_PROGRAMS_TESTS ${TEMPLATE_FOR_PROGRAMS_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_PROGRAMS_MAIN_SOURCES ${TEMPLATE_FOR_PROGRAMS_MAIN_DIRECTORY})

set(TEMPLATE_FOR_PROGRAMS_SOURCES_AND_TESTS ${TEMPLATE_FOR_PROGRAMS_SOURCES} ${TEMPLATE_FOR_PROGRAMS_TESTS})
