set(HEART_TEE_SOURCE_DIRECTORY
    ${HEART_TEE_DIR}/src
)

set(HEART_TEE_TEST_DIRECTORY
    ${HEART_TEE_DIR}/tst
)

set(HEART_TEE_MAIN_DIRECTORY
    ${HEART_TEE_DIR}/main
)

set(HEART_TEE_INCLUDE_DIRECTORIES
    ${HEART_TEE_SOURCE_DIRECTORY}
)

set(HEART_TEE_TEST_INCLUDE_DIRECTORIES
    ${HEART_TEE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${HEART_TEE_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(HEART_TEE_SOURCES ${HEART_TEE_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${HEART_TEE_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(HEART_TEE_TESTS ${HEART_TEE_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${HEART_TEE_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(HEART_TEE_MAIN_SOURCES ${HEART_TEE_MAIN_DIRECTORY})

set(HEART_TEE_SOURCES_AND_TESTS
    ${HEART_TEE_SOURCES}
    ${HEART_TEE_TESTS}
)
