set(CHESS_COMBI_SOURCE_DIRECTORY
    ${CHESS_COMBI_DIR}/src
)

set(CHESS_COMBI_TEST_DIRECTORY
    ${CHESS_COMBI_DIR}/tst
)

set(CHESS_COMBI_MAIN_DIRECTORY
    ${CHESS_COMBI_DIR}/main
)

set(CHESS_COMBI_INCLUDE_DIRECTORIES
    ${CHESS_COMBI_SOURCE_DIRECTORY}
)

set(CHESS_COMBI_TEST_INCLUDE_DIRECTORIES
    ${CHESS_COMBI_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${CHESS_COMBI_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CHESS_COMBI_SOURCES ${CHESS_COMBI_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${CHESS_COMBI_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CHESS_COMBI_TESTS ${CHESS_COMBI_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${CHESS_COMBI_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(CHESS_COMBI_MAIN_SOURCES ${CHESS_COMBI_MAIN_DIRECTORY})

set(CHESS_COMBI_SOURCES_AND_TESTS
    ${CHESS_COMBI_SOURCES}
    ${CHESS_COMBI_TESTS}
)
