set(C_PLUS_PLUS_EXAMPLES_SOURCE_DIRECTORY
    ${C_PLUS_PLUS_EXAMPLES_DIR}/src
)

set(C_PLUS_PLUS_EXAMPLES_TEST_DIRECTORY
    ${C_PLUS_PLUS_EXAMPLES_DIR}/tst
)

set(C_PLUS_PLUS_EXAMPLES_MAIN_DIRECTORY
    ${C_PLUS_PLUS_EXAMPLES_DIR}/main
)

set(C_PLUS_PLUS_EXAMPLES_INCLUDE_DIRECTORIES
    ${C_PLUS_PLUS_EXAMPLES_SOURCE_DIRECTORY}
)

set(C_PLUS_PLUS_EXAMPLES_TEST_INCLUDE_DIRECTORIES
    ${C_PLUS_PLUS_EXAMPLES_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${C_PLUS_PLUS_EXAMPLES_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(C_PLUS_PLUS_EXAMPLES_SOURCES ${C_PLUS_PLUS_EXAMPLES_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${C_PLUS_PLUS_EXAMPLES_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(C_PLUS_PLUS_EXAMPLES_TESTS ${C_PLUS_PLUS_EXAMPLES_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${C_PLUS_PLUS_EXAMPLES_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(C_PLUS_PLUS_EXAMPLES_MAIN_SOURCES ${C_PLUS_PLUS_EXAMPLES_MAIN_DIRECTORY})

set(C_PLUS_PLUS_EXAMPLES_SOURCES_AND_TESTS
    ${C_PLUS_PLUS_EXAMPLES_SOURCES}
    ${C_PLUS_PLUS_EXAMPLES_TESTS}
)
