set(APRG_PROCESS_FILES_SOURCE_DIRECTORY ${APRG_PROCESS_FILES_DIR}/src)

set(APRG_PROCESS_FILES_TEST_DIRECTORY ${APRG_PROCESS_FILES_DIR}/tst)

set(APRG_PROCESS_FILES_INCLUDE_DIRECTORIES ${APRG_PROCESS_FILES_SOURCE_DIRECTORY})

set(APRG_PROCESS_FILES_TEST_INCLUDE_DIRECTORIES ${APRG_PROCESS_FILES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_PROCESS_FILES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_PROCESS_FILES_SOURCES ${APRG_PROCESS_FILES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_PROCESS_FILES_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_PROCESS_FILES_TESTS ${APRG_PROCESS_FILES_TEST_DIRECTORY})

set(APRG_PROCESS_FILES_SOURCES_AND_TESTS ${APRG_PROCESS_FILES_SOURCES} ${APRG_PROCESS_FILES_TESTS})
