set(APRG_PROCESS_FILES_SOURCE_DIRECTORY
    ${APRG_PROCESS_FILES_DIR}/src
)

set(APRG_PROCESS_FILES_TEST_DIRECTORY
    ${APRG_PROCESS_FILES_DIR}/tst
)

set(APRG_PROCESS_FILES_INCLUDE_DIRECTORIES
    ${APRG_PROCESS_FILES_SOURCE_DIRECTORY}
)

set(APRG_PROCESS_FILES_TEST_INCLUDE_DIRECTORIES
    ${APRG_PROCESS_FILES_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${APRG_PROCESS_FILES_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_PROCESS_FILES_SOURCES APRG_PROCESS_FILES_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${APRG_PROCESS_FILES_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_PROCESS_FILES_TESTS APRG_PROCESS_FILES_TEST_DIRECTORY)

set(APRG_PROCESS_FILES_SOURCES_AND_TESTS
    ${APRG_PROCESS_FILES_SOURCES}
    ${APRG_PROCESS_FILES_TESTS}
)
