set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/src)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/tst)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/main)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_INCLUDE_DIRECTORIES ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY})

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_INCLUDE_DIRECTORIES ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY}]")
get_source_files_from_directory(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES
                                ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY}]")
get_source_files_from_directory(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TESTS
                                ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY}]")
get_source_files_from_directory(ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_SOURCES
                                ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY})

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES_AND_TESTS ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES}
                                                         ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TESTS})
