set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/src
)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/tst
)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_DIR}/main
)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_INCLUDE_DIRECTORIES
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY}
)

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_INCLUDE_DIRECTORIES
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for sources C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCE_DIRECTORY})

PRINT_STATUS("Looking for tests C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(ASIL_BASEBAND_POOLING_AND_PROGRAMS_TESTS ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TEST_DIRECTORY})

PRINT_STATUS("Looking for main C/C++ files in: [${ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_SOURCES ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_MAIN_DIRECTORY})

set(ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES_AND_TESTS
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_SOURCES}
    ${ASIL_BASEBAND_POOLING_AND_PROGRAMS_TESTS}
)
