set(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCE_DIRECTORY ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_DIR}/src)

set(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TEST_DIRECTORY ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_DIR}/tst)

set(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_INCLUDE_DIRECTORIES ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCE_DIRECTORY})

set(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TEST_INCLUDE_DIRECTORIES ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCE_DIRECTORY}]")
get_source_files_from_directory(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCES
                                ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TEST_DIRECTORY}]")
get_source_files_from_directory(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TESTS
                                ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TEST_DIRECTORY})

set(LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCES_AND_TESTS ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_SOURCES}
                                                        ${LRM_DSS_WCDMA_LTE_LOAD_MONITORING_TESTS})
