set(CHESS_PEEK_SOURCE_DIRECTORY ${CHESS_PEEK_DIR}/src)

set(CHESS_PEEK_TEST_DIRECTORY ${CHESS_PEEK_DIR}/tst)

set(CHESS_PEEK_MAIN_DIRECTORY ${CHESS_PEEK_DIR}/main)

set(CHESS_PEEK_INCLUDE_DIRECTORIES ${CHESS_PEEK_SOURCE_DIRECTORY})

set(CHESS_PEEK_TEST_INCLUDE_DIRECTORIES ${CHESS_PEEK_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${CHESS_PEEK_SOURCE_DIRECTORY}]")
get_source_files_from_directory(CHESS_PEEK_SOURCES ${CHESS_PEEK_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${CHESS_PEEK_TEST_DIRECTORY}]")
get_source_files_from_directory(CHESS_PEEK_TESTS ${CHESS_PEEK_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${CHESS_PEEK_MAIN_DIRECTORY}]")
get_source_files_from_directory(CHESS_PEEK_MAIN_SOURCES ${CHESS_PEEK_MAIN_DIRECTORY})

set(CHESS_PEEK_SOURCES_AND_TESTS ${CHESS_PEEK_SOURCES} ${CHESS_PEEK_TESTS})
