set(APRG_GNU_PLOT_SOURCE_DIRECTORY
    ${APRG_GNU_PLOT_DIR}/src
)

set(APRG_GNU_PLOT_TEST_DIRECTORY
    ${APRG_GNU_PLOT_DIR}/tst
)

set(APRG_GNU_PLOT_INCLUDE_DIRECTORIES
    ${APRG_GNU_PLOT_SOURCE_DIRECTORY}
)

set(APRG_GNU_PLOT_TEST_INCLUDE_DIRECTORIES
    ${APRG_GNU_PLOT_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${APRG_GNU_PLOT_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_GNU_PLOT_SOURCES APRG_GNU_PLOT_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${APRG_GNU_PLOT_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_GNU_PLOT_TESTS APRG_GNU_PLOT_TEST_DIRECTORY)

set(APRG_GNU_PLOT_SOURCES_AND_TESTS
    ${APRG_GNU_PLOT_SOURCES}
    ${APRG_GNU_PLOT_TESTS}
)
