set(TEMPLATE_FOR_ALL_CASES_SOURCE_DIRECTORY ${TEMPLATE_FOR_ALL_CASES_DIR}/src)

set(TEMPLATE_FOR_ALL_CASES_TEST_DIRECTORY ${TEMPLATE_FOR_ALL_CASES_DIR}/tst)

set(TEMPLATE_FOR_ALL_CASES_MAIN_DIRECTORY ${TEMPLATE_FOR_ALL_CASES_DIR}/main)

set(TEMPLATE_FOR_ALL_CASES_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_ALL_CASES_SOURCE_DIRECTORY})

set(TEMPLATE_FOR_ALL_CASES_TEST_INCLUDE_DIRECTORIES ${TEMPLATE_FOR_ALL_CASES_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${TEMPLATE_FOR_ALL_CASES_SOURCE_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_ALL_CASES_SOURCES ${TEMPLATE_FOR_ALL_CASES_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${TEMPLATE_FOR_ALL_CASES_TEST_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_ALL_CASES_TESTS ${TEMPLATE_FOR_ALL_CASES_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${TEMPLATE_FOR_ALL_CASES_MAIN_DIRECTORY}]")
get_source_files_from_directory(TEMPLATE_FOR_ALL_CASES_MAIN_SOURCES ${TEMPLATE_FOR_ALL_CASES_MAIN_DIRECTORY})

set(TEMPLATE_FOR_ALL_CASES_SOURCES_AND_TESTS ${TEMPLATE_FOR_ALL_CASES_SOURCES} ${TEMPLATE_FOR_ALL_CASES_TESTS})
