set(APRG_BITMAP_SOURCE_DIRECTORY ${APRG_BITMAP_DIR}/src)

set(APRG_BITMAP_TEST_DIRECTORY ${APRG_BITMAP_DIR}/tst)

set(APRG_BITMAP_INCLUDE_DIRECTORIES ${APRG_BITMAP_SOURCE_DIRECTORY})

set(APRG_BITMAP_TEST_INCLUDE_DIRECTORIES ${APRG_BITMAP_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_BITMAP_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_BITMAP_SOURCES ${APRG_BITMAP_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_BITMAP_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_BITMAP_TESTS ${APRG_BITMAP_TEST_DIRECTORY})

set(APRG_BITMAP_SOURCES_AND_TESTS ${APRG_BITMAP_SOURCES} ${APRG_BITMAP_TESTS})
