set(APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY
    ${APRG_GREP_STRING_EVALUATOR_DIR}/src
)

set(APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY
    ${APRG_GREP_STRING_EVALUATOR_DIR}/tst
)

set(APRG_GREP_STRING_EVALUATOR_INCLUDE_DIRECTORIES
    ${APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY}
)

set(APRG_GREP_STRING_EVALUATOR_TEST_INCLUDE_DIRECTORIES
    ${APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC C/C++ files in: [${APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_GREP_STRING_EVALUATOR_SOURCES APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY)

PRINT_STATUS("Looking for TST C/C++ files in: [${APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY}]")
GET_SOURCE_FILES_FROM_DIRECTORY(APRG_GREP_STRING_EVALUATOR_TESTS APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY)

set(APRG_GREP_STRING_EVALUATOR_SOURCES_AND_TESTS
    ${APRG_GREP_STRING_EVALUATOR_SOURCES}
    ${APRG_GREP_STRING_EVALUATOR_TESTS}
)
