set(APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY ${APRG_GREP_STRING_EVALUATOR_DIR}/src)

set(APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY ${APRG_GREP_STRING_EVALUATOR_DIR}/tst)

set(APRG_GREP_STRING_EVALUATOR_INCLUDE_DIRECTORIES ${APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY})

set(APRG_GREP_STRING_EVALUATOR_TEST_INCLUDE_DIRECTORIES ${APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_GREP_STRING_EVALUATOR_SOURCES ${APRG_GREP_STRING_EVALUATOR_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_GREP_STRING_EVALUATOR_TESTS ${APRG_GREP_STRING_EVALUATOR_TEST_DIRECTORY})

set(APRG_GREP_STRING_EVALUATOR_SOURCES_AND_TESTS ${APRG_GREP_STRING_EVALUATOR_SOURCES}
                                                 ${APRG_GREP_STRING_EVALUATOR_TESTS})
