set(RAGNAROK_ONLINE_SOURCE_DIRECTORY ${RAGNAROK_ONLINE_DIR}/src)

set(RAGNAROK_ONLINE_TEST_DIRECTORY ${RAGNAROK_ONLINE_DIR}/tst)

set(RAGNAROK_ONLINE_MAIN_DIRECTORY ${RAGNAROK_ONLINE_DIR}/main)

set(RAGNAROK_ONLINE_INCLUDE_DIRECTORIES ${RAGNAROK_ONLINE_SOURCE_DIRECTORY})

set(RAGNAROK_ONLINE_TEST_INCLUDE_DIRECTORIES ${RAGNAROK_ONLINE_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${RAGNAROK_ONLINE_SOURCE_DIRECTORY}]")
get_source_files_from_directory(RAGNAROK_ONLINE_SOURCES ${RAGNAROK_ONLINE_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${RAGNAROK_ONLINE_TEST_DIRECTORY}]")
get_source_files_from_directory(RAGNAROK_ONLINE_TESTS ${RAGNAROK_ONLINE_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${RAGNAROK_ONLINE_MAIN_DIRECTORY}]")
get_source_files_from_directory(RAGNAROK_ONLINE_MAIN_SOURCES ${RAGNAROK_ONLINE_MAIN_DIRECTORY})

set(RAGNAROK_ONLINE_SOURCES_AND_TESTS ${RAGNAROK_ONLINE_SOURCES} ${RAGNAROK_ONLINE_TESTS})
