set(PID_SIMULATOR_SOURCE_DIRECTORY ${PID_SIMULATOR_DIR}/src)

set(PID_SIMULATOR_TEST_DIRECTORY ${PID_SIMULATOR_DIR}/tst)

set(PID_SIMULATOR_MAIN_DIRECTORY ${PID_SIMULATOR_DIR}/main)

set(PID_SIMULATOR_INCLUDE_DIRECTORIES ${PID_SIMULATOR_SOURCE_DIRECTORY})

set(PID_SIMULATOR_TEST_INCLUDE_DIRECTORIES ${PID_SIMULATOR_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${PID_SIMULATOR_SOURCE_DIRECTORY}]")
get_source_files_from_directory(PID_SIMULATOR_SOURCES ${PID_SIMULATOR_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${PID_SIMULATOR_TEST_DIRECTORY}]")
get_source_files_from_directory(PID_SIMULATOR_TESTS ${PID_SIMULATOR_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${PID_SIMULATOR_MAIN_DIRECTORY}]")
get_source_files_from_directory(PID_SIMULATOR_MAIN_SOURCES ${PID_SIMULATOR_MAIN_DIRECTORY})

set(PID_SIMULATOR_SOURCES_AND_TESTS ${PID_SIMULATOR_SOURCES} ${PID_SIMULATOR_TESTS})
