set(APRG_ALGORITHM_SOURCE_DIRECTORY ${APRG_ALGORITHM_DIR}/src)

set(APRG_ALGORITHM_TEST_DIRECTORY ${APRG_ALGORITHM_DIR}/tst)

set(APRG_ALGORITHM_INCLUDE_DIRECTORIES ${APRG_ALGORITHM_SOURCE_DIRECTORY})

set(APRG_ALGORITHM_TEST_INCLUDE_DIRECTORIES ${APRG_ALGORITHM_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${APRG_ALGORITHM_SOURCE_DIRECTORY}]")
get_source_files_from_directory(APRG_ALGORITHM_SOURCES ${APRG_ALGORITHM_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${APRG_ALGORITHM_TEST_DIRECTORY}]")
get_source_files_from_directory(APRG_ALGORITHM_TESTS ${APRG_ALGORITHM_TEST_DIRECTORY})

set(APRG_ALGORITHM_SOURCES_AND_TESTS ${APRG_ALGORITHM_SOURCES} ${APRG_ALGORITHM_TESTS})
