set(FESTER_ROBOT_SOURCE_DIRECTORY ${FESTER_ROBOT_DIR}/src)

set(FESTER_ROBOT_TEST_DIRECTORY ${FESTER_ROBOT_DIR}/tst)

set(FESTER_ROBOT_MAIN_DIRECTORY ${FESTER_ROBOT_DIR}/main)

set(FESTER_ROBOT_INCLUDE_DIRECTORIES ${FESTER_ROBOT_SOURCE_DIRECTORY})

set(FESTER_ROBOT_TEST_INCLUDE_DIRECTORIES ${FESTER_ROBOT_TEST_DIRECTORY})

print_status("Looking for sources C/C++ files in: [${FESTER_ROBOT_SOURCE_DIRECTORY}]")
get_source_files_from_directory(FESTER_ROBOT_SOURCES ${FESTER_ROBOT_SOURCE_DIRECTORY})

print_status("Looking for tests C/C++ files in: [${FESTER_ROBOT_TEST_DIRECTORY}]")
get_source_files_from_directory(FESTER_ROBOT_TESTS ${FESTER_ROBOT_TEST_DIRECTORY})

print_status("Looking for main C/C++ files in: [${FESTER_ROBOT_MAIN_DIRECTORY}]")
get_source_files_from_directory(FESTER_ROBOT_MAIN_SOURCES ${FESTER_ROBOT_MAIN_DIRECTORY})

set(FESTER_ROBOT_SOURCES_AND_TESTS ${FESTER_ROBOT_SOURCES} ${FESTER_ROBOT_TESTS})
